name: pgsr
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=11.8
  - mkl=2024.0.0
  - numpy=1.23.5
  - plyfile
  - python=3.9
  - pip=22.3.1
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - pip:
    - "git+https://github.com/facebookresearch/pytorch3d.git@v0.7.7"
    - open3d
    - opencv-python
    - lpips
    - trimesh
    - tensorboard
    - submodules/diff-plane-rasterization
    - submodules/simple-knn
